"use client";
import {useEffect,useState} from "react";
const I=({value,onChange,placeholder,type="text"})=><input className="w-full rounded-lg border border-border-subtle bg-surface-2 px-3 py-2 text-sm mb-2" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} type={type}/>;
export default function OfficePage(){
 const [d,setD]=useState(null),[active,setActive]=useState(null),[msg,setMsg]=useState(""),[status,setStatus]=useState("");
 const [room,setRoom]=useState("Main Office"),[p,setP]=useState({name:"OpenAI Compatible",baseUrl:"https://api.openai.com/v1",apiKey:"",model:""}),[c,setC]=useState({name:"Mika",personality:"Friendly coding assistant",systemPrompt:"You are a helpful assistant inside the Multiver Office.",providerId:"",roomId:""});
 const load=()=>fetch("/api/office",{cache:"no-store"}).then(r=>r.json()).then(setD);useEffect(load,[]);
 const act=async(b)=>{try{const r=await fetch("/api/office",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)}),x=await r.json();if(!r.ok)throw Error(x.error);setD(x);setStatus("Tersimpan")}catch(e){setStatus(e.message)}};
 const send=async()=>{if(!active||!msg.trim())return;setStatus("Berpikir…");try{const r=await fetch("/api/office/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({characterId:active.id,message:msg})});if(!r.ok)throw Error((await r.json()).error);await r.body?.cancel();setMsg("");await load();setStatus("Selesai")}catch(e){setStatus(e.message)}};
 if(!d)return <div className="p-6">Memuat Office…</div>;
 return <main className="p-4 md:p-6 space-y-4"><section className="rounded-xl border border-border-subtle bg-vibrancy p-4"><h1 className="text-xl font-semibold">Office Bot</h1><p className="text-sm text-text-muted">Workspace pixel-art ringan untuk bot, pet, NPC, dan karakter AI.</p></section>
 <div className="grid lg:grid-cols-[1.4fr_.8fr] gap-4"><section className="rounded-xl border border-border-subtle bg-vibrancy p-4"><div className="aspect-video rounded-xl border-4 border-[#8b7355] bg-[#cdb78f] relative overflow-hidden" style={{backgroundImage:"linear-gradient(#0000 95%,#b89f78 95%),linear-gradient(90deg,#0000 95%,#b89f78 95%)",backgroundSize:"32px 32px"}}><div className="absolute left-[40%] top-[24%] w-28 h-16 bg-[#6b7280] border-4 border-[#374151]"/>{d.characters.map((x,i)=><button key={x.id} onClick={()=>setActive(x)} className="absolute" style={{left:(15+i*18)+"%",top:(45+(i%2)*18)+"%"}}><div className="w-12 h-12 bg-[#4b5563] border-4 border-[#1f2937]"/><span className="text-xs bg-white px-2 rounded">{x.name}</span></button>)}</div>{active&&<div className="mt-3 flex gap-2"><input className="flex-1 rounded-lg border border-border-subtle bg-surface-2 px-3 py-2 text-sm" value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==="Enter"&&!e.shiftKey&&(e.preventDefault(),send())} placeholder="Bicara dengan bot…"/><button onClick={send} className="px-4 rounded-lg bg-primary text-white">Kirim</button></div>}</section>
 <aside className="space-y-4"><section className="rounded-xl border border-border-subtle bg-vibrancy p-4"><h2 className="font-semibold mb-2">Ruang</h2><div className="flex gap-2"><I value={room} onChange={setRoom} placeholder="Nama ruang"/><button onClick={()=>act({action:"create-room",name:room})} className="px-3 rounded-lg bg-primary text-white h-10">+</button></div>{d.rooms.map(x=><div key={x.id} className="flex justify-between text-sm py-1"><span>{x.name}</span><button className="text-red-500" onClick={()=>act({action:"delete-room",id:x.id})}>Hapus</button></div>)}</section>
 <section className="rounded-xl border border-border-subtle bg-vibrancy p-4"><h2 className="font-semibold mb-2">Provider</h2><I value={p.name} onChange={v=>setP({...p,name:v})} placeholder="Nama"/><I value={p.baseUrl} onChange={v=>setP({...p,baseUrl:v})} placeholder="Base URL"/><I value={p.model} onChange={v=>setP({...p,model:v})} placeholder="Model"/><I value={p.apiKey} onChange={v=>setP({...p,apiKey:v})} placeholder="API Key" type="password"/><button onClick={()=>act({action:"create-provider",...p})} className="w-full py-2 rounded-lg bg-primary text-white">Simpan Provider</button><p className="text-xs text-text-muted mt-2">API key disimpan terenkripsi dan tidak dikembalikan ke browser.</p></section>
 <section className="rounded-xl border border-border-subtle bg-vibrancy p-4"><h2 className="font-semibold mb-2">Karakter</h2><I value={c.name} onChange={v=>setC({...c,name:v})} placeholder="Nama"/><I value={c.personality} onChange={v=>setC({...c,personality:v})} placeholder="Personality"/><I value={c.systemPrompt} onChange={v=>setC({...c,systemPrompt:v})} placeholder="System prompt"/><select className="w-full rounded-lg border border-border-subtle bg-surface-2 px-3 py-2 text-sm mb-2" value={c.providerId} onChange={e=>setC({...c,providerId:e.target.value})}><option value="">Pilih provider</option>{d.providers.map(x=><option key={x.id} value={x.id}>{x.name} — {x.model}</option>)}</select><select className="w-full rounded-lg border border-border-subtle bg-surface-2 px-3 py-2 text-sm mb-2" value={c.roomId} onChange={e=>setC({...c,roomId:e.target.value})}><option value="">Pilih ruang</option>{d.rooms.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button onClick={()=>act({action:"create-character",...c})} className="w-full py-2 rounded-lg bg-primary text-white">Tambah Karakter</button>{d.characters.map(x=><div key={x.id} className="flex justify-between text-xs py-1"><button onClick={()=>setActive(x)}>{x.name}</button><button className="text-red-500" onClick={()=>act({action:"delete-character",id:x.id})}>Hapus</button></div>)}</section></aside></div><p className="text-xs text-text-muted">{status}</p></main>
}
